// <auto-generated />
namespace UniversityCourseMnagementSystemWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Course_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261117232_Course_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
