// <auto-generated />
namespace UniversityCourseMnagementSystemWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Semester_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Semester_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261050046_Semester_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
